registru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sales.urls")),
    path("users/", include("users.urls")),
]

sales/urls.py
from django.urls import path
from . import views
from .views import (
    ProductInfoCreateView,
    ProductInfoListView,
    ProductInfoDetailView,
    ProductInfoUpdateView,
    ProductInfoDeleteView,
)
from django.conf import settings
from django.conf.urls.static import static

app_name = "sales"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_plan", views.add_plan, name="add_plan"),
    path("plan/<int:pk>", views.plan, name="plan"),
    path("visits", views.visits, name="visits"),
    path("visit/<int:visit_id>/", views.visit, name="visit"),
    path("visits/select_client", views.select_client, name="select_client"),
    path(
        "visits/<str:client>/select_shop/<str:source>/",
        views.select_shop,
        name="select_shop",
    ),
    path("visits/<int:shop_id>/new_visit/", views.new_visit, name="new_visit"),
    path("info_competition", views.info_competition, name="competition"),
    path("plans_reports/", views.plans_reports, name="plans_reports"),
    path(
        "plans_reports/current/<int:pk>/",
        views.agent_plan_current,
        name="agent_plan_current",
    ),
    path(
        "plans_reports/history/<int:pk>/",
        views.agent_plan_history,
        name="agent_plan_history",
    ),
    path("visits_reports", views.visits_reports, name="visits_reports"),
    path(
        "visits_reports/by_agent_and_client/",
        views.visits_by_agent_and_client,
        name="by_agent_and_client",
    ),
    path("visits_reports/by_product/", views.visits_by_product, name="by_product"),
    path(
        "visits_reports/export_storechecks/",
        views.export_storechecks,
        name="export_storechecks",
    ),
    path("competition_reports", views.competition_reports, name="competition_reports"),
    path(
        "competition_reports/export_competition/",
        views.export_competition,
        name="export_competition",
    ),
    path(
        "competition_reports/by_product_and_agent/",
        views.by_product_and_agent,
        name="by_product_and_agent",
    ),
    path(
        "competition_reports/by_category_and_agent/",
        views.by_category_and_agent,
        name="by_category_and_agent",
    ),
    path(
        "competition_reports/by_producer_and_agent/",
        views.by_producer_and_agent,
        name="by_producer_and_agent",
    ),
    path("productinfo_list", ProductInfoListView.as_view(), name="productinfo_list"),
    path(
        "productinfo/<int:pk>/",
        ProductInfoDetailView.as_view(),
        name="productinfo_detail",
    ),
    path("productinfo/new/", ProductInfoCreateView.as_view(), name="productinfo_new"),
    path(
        "productinfo/<int:pk>/edit/",
        ProductInfoUpdateView.as_view(),
        name="productinfo_edit",
    ),
    path(
        "productinfo/<int:pk>/delete/",
        ProductInfoDeleteView.as_view(),
        name="productinfo_delete",
    ),
    path("priceinfo/<int:shop_id>/", views.price_info_collect, name="priceinfo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("employee_list/", views.employees, name="employees"),
    path("employee/<int:user_id>/", views.profile, name="profile"),
    path("edit_profile/<int:user_id>/", views.edit_profile, name="edit_profile"),
    path("", include("django.contrib.auth.urls")),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.
class Department(models.Model):
    name = models.CharField("Nume Departament", max_length=60)

    class Meta:
        verbose_name = "departament"
        verbose_name_plural = "departamente"

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField("Nume Locatie", max_length=60)

    class Meta:
        verbose_name = "locatie"
        verbose_name_plural = "locatii"

    def __str__(self):
        return self.name


class CustUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError("Este necesara adresa de email")
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_active=True,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **extra_fields
        )

        user.set_password(password)
        user.save()
        return user

    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True)
    username = models.CharField(max_length=150, blank=True, unique=False)
    first_name = models.CharField(max_length=254, blank=True)
    last_name = models.CharField(max_length=254, blank=True)
    phone = models.CharField(blank=True, max_length=30)
    hire_date = models.DateField(blank=True, null=True)
    position = models.CharField(max_length=150, blank=True)
    department = models.ForeignKey(Department, blank=True, null=True, on_delete=models.SET_NULL)
    location = models.ForeignKey(Location, blank=True, null=True, on_delete=models.SET_NULL)
    birthday = models.DateField(blank=True, null=True)

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustUserManager()

    class Meta:
        verbose_name = "utilizator"
        verbose_name_plural = "utilizatori"

    def __str__(self):
        name = self.first_name + " " + self.last_name
        return name

users/forms.py
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "phone",
            "position",
            "department",
            "location",
            "hire_date",
            "birthday",
        ]

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.http import Http404

from .models import User
from .forms import UserForm


# Create your views here.
def index(request):
    return render(request, "index.html")


def employees(request):
    employees = User.objects.all().order_by("last_name")
    context = {"employees": employees}
    return render(request, "employee_list.html", context)


def profile(request, user_id):
    profile = User.objects.get(id=user_id)
    context = {"profile": profile}
    return render(request, "profile.html", context)


def edit_profile(request, user_id):
    profile = User.objects.get(id=user_id)
    if request.method == "POST":
        form = UserForm(instance=profile, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:profile", user_id=user_id)
        else:
            print(form.errors)
    else:
        form = UserForm(instance=profile)

    context = {"profile": profile, "form": form}
    return render(request, "edit_profile.html", context)

users/templates/edit_profile.html
{% extends "sales/base.html" %}

{% block page_header %}
<section class="container">
	<h1>{{ user.first_name }} {{ user.last_name }}</h1>
</section>
	
{% endblock page_header %}

{% block content %}
<section class="container">
	<form action="{% url 'users:edit_profile' user.id %}" method='post' class="form">
		<!-- <table class="table table-sm"> -->
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-primary" >Salvează modificările</button>
	</form>
</section>
{% endblock content %}

users/templates/employee_list.html
{% extends "sales/base.html" %}

{% block page_header %}
<section class="container">
	<div class="row">
		<h2>Angajații companiei</h2>
	</div>
</section>
{% endblock page_header %}

{% block content %}
<section class="container">
	<div class="row">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col">Nume</th>
					<th scope="col">Email</th>
					<th scope="col">Telefon</th>
					<th scope="col">Funcție</th>
					<th scope="col">Departament</th>
					<th scope="col">Locație</th>
					<th scope="col">Data angajării</th>
					<th scope="col">Data nașterii</th>
				</tr>
			</thead>
			{% for employee in employees %}
			<tbody>
				<tr>
					<td>{{ employee.first_name }} {{ employee.last_name }}</td>
					<td>{{ employee.email }}</td>
					<td>{{ employee.phone }}</td>
					<td>{{ employee.position }}</td>
					<td>{{ employee.department }}</td>
					<td>{{ employee.location }}</td>
					<td>{{ employee.hire_date|date:'d M Y' }}</td>
					<td>{{ employee.birthday|date:'d M Y' }}</td>
				</tr>
			</tbody>
			{% endfor %}
		</table>
	</div>
</section>
{% endblock content %}

users/templates/profile.html
{% extends "sales/base.html" %}

{% block page_header %}
<section class="container">
	<h1>{{ user.first_name }} {{ user.last_name }}</h1>
	<a href="{% url 'users:edit_profile' user.id %}"class="btn btn-primary">Editează</a>
</section>
	
{% endblock page_header %}

{% block content %}
<section class="container">
	<table class="table">
		<tr>
			<td>Prenume</td>
			<td>{{ user.first_name }}</td>
		</tr>
		<tr>
			<td>Nume</td>
			<td>{{ user.last_name }}</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>{{ user.email }}</td>
		</tr>
		<tr>
			<td>Telefon</td>
			<td>{{ user.phone }}</td>
		</tr>
		<tr>
			<td>Funcție</td>
			<td>{{ user.position }}</td>
		</tr>
		<tr>
			<td>Departament</td>
			<td>{{ user.department }}</td>
		</tr>
		<tr>
			<td>Locație</td>
			<td>{{ user.location }}</td>
		</tr>
		<tr>
			<td>Data angajării</td>
			<td>{{ user.hire_date }}</td>
		</tr>
		<tr>
			<td>Data nașterii</td>
			<td>{{ user.birthday }}</td>
		</tr>
	</table>
</section>
{% endblock content %}