registru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sales.urls")),
    path("users/", include("users.urls")),
]

sales/urls.py
from django.urls import path
from . import views
from .views import (
    ProductInfoCreateView,
    ProductInfoListView,
    ProductInfoDetailView,
    ProductInfoUpdateView,
    ProductInfoDeleteView,
)
from django.conf import settings
from django.conf.urls.static import static

app_name = "sales"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_plan", views.add_plan, name="add_plan"),
    path("plan/<int:pk>", views.plan, name="plan"),
    path("visits", views.visits, name="visits"),
    path("visit/<int:visit_id>/", views.visit, name="visit"),
    path("visits/select_client", views.select_client, name="select_client"),
    path(
        "visits/<str:client>/select_shop/<str:source>/",
        views.select_shop,
        name="select_shop",
    ),
    path("visits/<int:shop_id>/new_visit/", views.new_visit, name="new_visit"),
    path("info_competition", views.info_competition, name="competition"),
    path("plans_reports/", views.plans_reports, name="plans_reports"),
    path(
        "plans_reports/current/<int:pk>/",
        views.agent_plan_current,
        name="agent_plan_current",
    ),
    path(
        "plans_reports/history/<int:pk>/",
        views.agent_plan_history,
        name="agent_plan_history",
    ),
    path("visits_reports", views.visits_reports, name="visits_reports"),
    path(
        "visits_reports/by_agent_and_client/",
        views.visits_by_agent_and_client,
        name="by_agent_and_client",
    ),
    path("visits_reports/by_product/", views.visits_by_product, name="by_product"),
    path(
        "visits_reports/export_storechecks/",
        views.export_storechecks,
        name="export_storechecks",
    ),
    path("competition_reports", views.competition_reports, name="competition_reports"),
    path(
        "competition_reports/export_competition/",
        views.export_competition,
        name="export_competition",
    ),
    path(
        "competition_reports/by_product_and_agent/",
        views.by_product_and_agent,
        name="by_product_and_agent",
    ),
    path(
        "competition_reports/by_category_and_agent/",
        views.by_category_and_agent,
        name="by_category_and_agent",
    ),
    path(
        "competition_reports/by_producer_and_agent/",
        views.by_producer_and_agent,
        name="by_producer_and_agent",
    ),
    path("productinfo_list", ProductInfoListView.as_view(), name="productinfo_list"),
    path(
        "productinfo/<int:pk>/",
        ProductInfoDetailView.as_view(),
        name="productinfo_detail",
    ),
    path("productinfo/new/", ProductInfoCreateView.as_view(), name="productinfo_new"),
    path(
        "productinfo/<int:pk>/edit/",
        ProductInfoUpdateView.as_view(),
        name="productinfo_edit",
    ),
    path(
        "productinfo/<int:pk>/delete/",
        ProductInfoDeleteView.as_view(),
        name="productinfo_delete",
    ),
    path("priceinfo/<int:shop_id>/", views.price_info_collect, name="priceinfo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Visit, Product, WeekPlan, PriceEntry
from datetime import date


class VisitForm(forms.ModelForm):

    date_created = forms.DateTimeField(
        label="Data vizitei",
        initial=date.today,
        input_formats=["%d/%m/%Y %H:%M"],
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form_input",
            },
        ),
    )

    products = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=[(product.pk, product.name) for product in Product.objects.all()],
        label="Lista de produse",
    )

    products_ordered = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=[(product.pk, product.name) for product in Product.objects.all()],
        label="Produse comandate",
    )

    shelf_image = forms.ImageField(required=False)

    observations = forms.CharField(widget=forms.Textarea(attrs={"rows": "5", "cols": "50"}))

    class Meta:
        model = Visit
        fields = "__all__"
        exclude = ("last-modified",)
        labels = {
            "agent": "Nume ASS",
            "client": "Client",
            "shop": "Magazin",
            "shelf_image": "Adauga imagine raft",
        }


class PlanForm(forms.ModelForm):
    start_date = forms.DateField(
        required=True,
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form_input",
            },
        ),
    )

    end_date = forms.DateField(
        required=True,
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form_input",
            },
        ),
    )

    class Meta:
        model = WeekPlan
        fields = "__all__"
        exclude = ("last-modified",)
        labels = {
            "monday_location": "Locație",
            "monday_goal": "Obiective",
            "monday_achieved": "Realizări",
            "tuesday_location": "Locație",
            "tuesday_goal": "Obiective",
            "tuesday_achieved": "Realizări",
            "wendsday_location": "Locație",
            "wendsday_goal": "Obiective",
            "wendsday_achieved": "Realizări",
            "thursday_location": "Locație",
            "thursday_goal": "Obiective",
            "thursday_achieved": "Realizări",
            "friday_location": "Locație",
            "friday_goal": "Obiective",
            "friday_achieved": "Realizări",
        }


class PriceEntryForm(forms.ModelForm):
    class Meta:
        model = PriceEntry
        fields = "__all__"
        exclude = (
            "date_created",
            "last-modified",
        )
        labels = {"agent": "Nume ASS", "client": "Client", "shop": "Magazin"}


PriceEntryFormSet = modelformset_factory(PriceEntry, fields=("product", "price_value"))

sales/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from datetime import date, timedelta
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
import csv

from .models import (
    Visit,
    Agent,
    WeekPlan,
    Product,
    Client,
    Shop,
    County,
    ProductInfo,
    PriceEntry,
    Category,
    Producer,
)
from .forms import VisitForm, PlanForm

# Set date variables
my_date = date.today()
week_day = my_date.weekday()
start_date = my_date - timedelta(days=week_day)
end_date = my_date + timedelta(days=(4 - week_day))


def index(request):
    # load homepage
    if request.method == "GET":
        if request.user.is_authenticated:
            # If the user is an agent, get visits and paginate them
            try:
                agent = Agent.objects.get(user_id=request.user)
                visits = Visit.objects.filter(agent=agent.id).order_by("-date_created")
            except Agent.DoesNotExist:
                agent = None
                return redirect("users:employees")
        else:
            return redirect("users:login")

        pk = request.GET.get("pk")

        week_plans = WeekPlan.objects.all().filter(agent=agent).order_by("-start_date")

        visits = Visit.objects.all().order_by("-date_created")
        paginator = Paginator(visits, 10)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        agent_counties = []
        counties = County.objects.all().order_by("name")

        # Select only the counties from agent's zone
        for county in counties:
            if county.zone == agent.zone:
                agent_counties.append(county)
        # The agent/user has no previous plans added, show blank form
        if not week_plans:
            plan = WeekPlan.objects.create(
                start_date=start_date,
                end_date=end_date,
                agent=agent,
                date_created=my_date,
            )
        else:
            # The plan is selected from homepage dropdown, show plan with specific pk
            if pk != None:
                plan = WeekPlan.objects.get(id=pk)
            # Automaticlly load the plan where today is within start_date and end_date of the plan
            else:
                plan = WeekPlan.objects.filter(agent=agent).latest("start_date")

        form = PlanForm(instance=plan)

        # get county for each day of the week
        if plan.monday_location != None:
            monday_location = int(plan.monday_location.id)
        elif request.GET.get("monday_location") != None:
            monday_location = int(request.GET.get("monday_location"))
        else:
            monday_location = None
        if plan.tuesday_location != None:
            tuesday_location = int(plan.tuesday_location.id)
        elif request.GET.get("tuesday_location") != None:
            tuesday_location = int(request.GET.get("tuesday_location"))
        else:
            tuesday_location = None
        if plan.wendsday_location != None:
            wendsday_location = int(plan.wendsday_location.id)
        elif request.GET.get("wendsday_location") != None:
            wendsday_location = int(request.GET.get("wendsday_location"))
        else:
            wendsday_location = None
        if plan.thursday_location != None:
            thursday_location = int(plan.thursday_location.id)
        elif request.GET.get("thursday_location") != None:
            thursday_location = int(request.GET.get("thursday_location"))
        else:
            thursday_location = None
        if plan.friday_location != None:
            friday_location = int(plan.friday_location.id)
        elif request.GET.get("friday_location") != None:
            friday_location = int(request.GET.get("friday_location"))
        else:
            friday_location = None

    # Save changes to currently showed plan
    elif request.method == "POST":
        form = PlanForm(request.POST, initial={"start_date": start_date, "end_date": end_date})
        if form.is_valid():
            new_plan = form.save(commit=False)
            agent = Agent.objects.get(user_id=request.user.id)
            new_plan.agent_id = agent.id
            new_plan.start_date = request.POST.get("start_date")
            new_plan.end_date = request.POST.get("end_date")
            monday_location = request.POST.get("monday_location")
            tuesday_location = request.POST.get("tuesday_location")
            wendsday_location = request.POST.get("wendsday_location")
            thursday_location = request.POST.get("thursday_location")
            friday_location = request.POST.get("friday_location")

            new_plan.id = request.POST.get("plan_id")
            new_plan.save()
            monday_location = str(new_plan.monday_location.id)
            return redirect("/" + "?monday_location=" + monday_location)
        else:
            print(form.errors)

    return render(
        request,
        "sales/index.html",
        {
            "form": form,
            "plan": plan,
            "page_obj": page_obj,
            "week_plans": week_plans,
            "agent_counties": agent_counties,
            "monday_location": monday_location,
            "tuesday_location": tuesday_location,
            "wendsday_location": wendsday_location,
            "thursday_location": thursday_location,
            "friday_location": friday_location,
            "agent": agent,
        },
    )


def add_plan(request):
    agent = Agent.objects.get(user_id=request.user.id)

    if request.method == "POST":
        form = PlanForm(data=request.POST)

        if form.is_valid():
            new_plan = form.save(commit=False)
            new_plan.agent_id = agent.id
            monday_location = request.POST.get("monday_location")
            tuesday_location = request.POST.get("tuesday_location")
            wendsday_location = request.POST.get("wendsday_location")
            thursday_location = request.POST.get("thursday_location")
            friday_location = request.POST.get("friday_location")
            new_plan.save()

        context = {
            "form": form,
            "monday_location": monday_location,
            "tuesday_location": tuesday_location,
            "wendsday_location": wendsday_location,
            "thursday_location": thursday_location,
            "friday_location": friday_location,
        }
        return redirect("sales:index")

    elif request.method == "GET":
        form = PlanForm()
        agent_counties = []
        counties = County.objects.all().order_by("name")
        for county in counties:
            if county.zone == agent.zone:
                agent_counties.append(county)

        context = {"form": form, "agent_counties": agent_counties}

    return render(request, "sales/add_plan.html", context)


def plan(request, pk):
    plan = WeekPlan.objects.get(id=pk)
    form = PlanForm()
    return render(request, "sales/plan.html", {"plan": plan, "form": form})


def visits(request):
    agent = Agent.objects.get(user_id=request.user.id)
    visits = Visit.objects.filter(agent=agent.id).order_by("-date_created")
    paginator = Paginator(visits, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "sales/visits.html", {"page_obj": page_obj})


def visit(request, visit_id):
    visit = Visit.objects.get(id=visit_id)
    products = visit.products.all()
    products_ordered = visit.products_ordered.all()
    return render(
        request,
        "sales/visit.html",
        {"visit": visit, "products": products, "products_ordered": products_ordered},
    )


def select_client(request):
    source = request.GET.get("source")
    if request.method == "GET":
        agent_clients = []
        clients = Client.objects.all()
        agent = Agent.objects.get(user=request.user)
        for client in clients:
            if client.zone == agent.zone:
                agent_clients.append(client.name)
        context = {"agent_clients": agent_clients, "source": source}

    elif request.method == "POST":
        client = request.POST.get("client")
        source = request.POST.get("source")
        context = {"client": client, "source": source}
        return redirect("sales:select_shop", client, source)

    return render(request, "sales/visits/select_client.html", context)


def select_shop(request, client, source):
    if request.method == "GET":
        client_obj = Client.objects.get(name=client)
        shop_list = client_obj.shop_set.all()
        context = {"shop_list": shop_list, "client": client, "source": source}
    elif request.method == "POST":
        shop_id = request.POST.get("shop")
        if source == "visits":
            return redirect("sales:new_visit", shop_id=shop_id)
        else:
            return redirect("sales:priceinfo", shop_id=shop_id)

    return render(request, "sales/visits/select_shop.html", context)


def new_visit(request, shop_id):
    shop = Shop.objects.get(id=shop_id)
    if request.method == "GET":
        form = VisitForm()
        context = {
            "form": form,
            "shop_id": shop_id,
            "client_name": shop.client.name,
            "shop_name": shop.name,
        }

    elif request.method == "POST":
        form = VisitForm(request.POST, request.FILES)
        if form.is_valid():
            agent = Agent.objects.get(user_id=request.user.id)
            client = shop.client
            date_created = form.cleaned_data.get("date_created")
            shelf_image = form.cleaned_data.get("shelf_image")
            quantity_ordered = form.cleaned_data.get("quantity_ordered")
            observations = form.cleaned_data.get("observations")
            visit = Visit.objects.create(

sales/templates/sales/storecheck_reports/by_agent_and_client.html
{% extends 'sales/base.html' %}

{% block content %}

<section class="container">
    <div class="row">
        {% if agent %}
        <h6>Afisez rezultate pentru: {{ agent }}</h6>
        {% else %}
        <h6>Toate vizitele</h6>
        {% endif %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Agent</th>
                    <th>Client</th>
                    <th>Magazin</th>
                    <th>Data</th>
                    <th>Produse la raft</th>
                    <th>Produse comandate</th>
                    <th>Detalii</th>
                </tr>
            </thead>
            <tbody>
                {% for visit in visits %}
                <tr>
                    <td>{{ visit.agent }}</td>
                    <td>{{ visit.client }}</td>
                    <td>{{ visit.shop }}</td>
                    <td>{{ visit.date_created}}</td>
                    <td>{{ visit.products.count }}</td>
                    <td>{{ visit.products_ordered.count }}</td>
                    <td><a href="{% url 'sales:visit' visit.id %}">Detalii</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}

sales/templates/sales/storecheck_reports/by_product.html
{% extends 'sales/base.html' %}

{% block content %}
<section class="container">
    <div class="row">
        <table clas="table table-hover">
            <thead>
                <tr>
                    <th>Agent</th>
                    <th>Data</th>
                    <th>Client</th>
                    <th>Magazin</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for visit in locations %}
                <tr>
                    <td>{{ visit.agent }}</td>
                    <td>{{ visit.date_created|date:"d M Y"}}</td>
                    <td>{{ visit.client }}</td>
                    <td> {{ visit.shop }}</td>
                    <td> <a href="">Detalii</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock %}

sales/templates/sales/storecheck_reports/visits_reports.html
{% extends 'sales/base.html' %}

{% block content %}
<main class="container">
    <section class="row">
        <div class="col">
            <h1>Rapoarte Storechecks</h1>
        </div>
    </section>
    <section class="row">
        <!-- ### BY AGENT/CLIENT (First type of search) ### -->
        <div class="col">
            <h3>Caută vizitele după agent și/sau client</h3>
            <p>Aceasta cautare iti arata o lista de vizite realizate de un agent, ordonate invers cronologic.</p>
            <form action="{% url 'sales:by_agent_and_client' %}" class="form" method="get">
                <label for="agents">Alege ASS:</label>
                <select name="a" id="agents">
                    <option disabled selected value> -- toți ASSii -- </option>
                    {% for agent in agents %}
                    <option value="{{ agent.id }}">{{ agent.user }}</option>
                    {% endfor %}
                </select>

                <label for="clients">Alege client:</label>
                <select name="c" id="clients">
                    <option disabled selected value> -- toți clientii -- </option>
                    {% for client in clients %}
                    <option value="{{ client.id }}">{{ client }}</option>
                    {% endfor %}
                </select>

                <label for="shops">Alege magazin:</label>
                <select name="s" id="shops">
                    <option disabled selected value> -- toate magazinele -- </option>
                    {% for shop in shops %}
                    <option value="{{ shop.id }}">{{ shop }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Caută" class="btn btn-primary">
            </form>
        </div>

        <!-- ### BY PRODUCT (Second type of search) ### -->
        <div class="col">
            <h3>Cauta dupa produs</h3>
            <p>Aceasta cautare iti va afisa o lista de magazine in care produsul a fost prezent la cel putin o vizita
                realizata in intervalul selectat de tine.</p>
            <form action="{% url 'sales:by_product' %}" class="form" method="get">
                <label for="products">Alege produs:</label>
                <select name="p" id="products">
                    <option disabled selected value> -- toate produsele -- </option>
                    {% for product in products %}
                    <option value="{{ product.id}}">{{ product }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Caută" class="btn btn-primary">
            </form>
        </div>

        <!-- ### EXPORTA DATELE -->
        <div class="col">
            <h3>Exporta datele</h3>
            <p>Genereaza un fisier csv care contine toate vizitele realizate pana in prezent de toti agentii. Fisierul
                csv poate fi deschis cu usurinta in Microsoft Excel.</p>
            <a href="{% url 'sales:export_storechecks' %}" class="btn btn-primary">Exporta in Excel</a>
        </div>

    </section>
</main>


{% endblock content %}