registru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sales.urls")),
    path("users/", include("users.urls")),
]

sales/urls.py
from django.urls import path
from . import views
from .views import (
    ProductInfoCreateView,
    ProductInfoListView,
    ProductInfoDetailView,
    ProductInfoUpdateView,
    ProductInfoDeleteView,
)
from django.conf import settings
from django.conf.urls.static import static

app_name = "sales"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_plan", views.add_plan, name="add_plan"),
    path("plan/<int:pk>", views.plan, name="plan"),
    path("visits", views.visits, name="visits"),
    path("visit/<int:visit_id>/", views.visit, name="visit"),
    path("visits/select_client", views.select_client, name="select_client"),
    path(
        "visits/<str:client>/select_shop/<str:source>/",
        views.select_shop,
        name="select_shop",
    ),
    path("visits/<int:shop_id>/new_visit/", views.new_visit, name="new_visit"),
    path("info_competition", views.info_competition, name="competition"),
    path("plans_reports/", views.plans_reports, name="plans_reports"),
    path(
        "plans_reports/current/<int:pk>/",
        views.agent_plan_current,
        name="agent_plan_current",
    ),
    path(
        "plans_reports/history/<int:pk>/",
        views.agent_plan_history,
        name="agent_plan_history",
    ),
    path("visits_reports", views.visits_reports, name="visits_reports"),
    path(
        "visits_reports/by_agent_and_client/",
        views.visits_by_agent_and_client,
        name="by_agent_and_client",
    ),
    path("visits_reports/by_product/", views.visits_by_product, name="by_product"),
    path(
        "visits_reports/export_storechecks/",
        views.export_storechecks,
        name="export_storechecks",
    ),
    path("competition_reports", views.competition_reports, name="competition_reports"),
    path(
        "competition_reports/export_competition/",
        views.export_competition,
        name="export_competition",
    ),
    path(
        "competition_reports/by_product_and_agent/",
        views.by_product_and_agent,
        name="by_product_and_agent",
    ),
    path(
        "competition_reports/by_category_and_agent/",
        views.by_category_and_agent,
        name="by_category_and_agent",
    ),
    path(
        "competition_reports/by_producer_and_agent/",
        views.by_producer_and_agent,
        name="by_producer_and_agent",
    ),
    path("productinfo_list", ProductInfoListView.as_view(), name="productinfo_list"),
    path(
        "productinfo/<int:pk>/",
        ProductInfoDetailView.as_view(),
        name="productinfo_detail",
    ),
    path("productinfo/new/", ProductInfoCreateView.as_view(), name="productinfo_new"),
    path(
        "productinfo/<int:pk>/edit/",
        ProductInfoUpdateView.as_view(),
        name="productinfo_edit",
    ),
    path(
        "productinfo/<int:pk>/delete/",
        ProductInfoDeleteView.as_view(),
        name="productinfo_delete",
    ),
    path("priceinfo/<int:shop_id>/", views.price_info_collect, name="priceinfo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("employee_list/", views.employees, name="employees"),
    path("employee/<int:user_id>/", views.profile, name="profile"),
    path("edit_profile/<int:user_id>/", views.edit_profile, name="edit_profile"),
    path("", include("django.contrib.auth.urls")),
]

sales/models.py
from django.db import models
from users.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField("Nume", max_length=120)

    class Meta:
        verbose_name = "gama"
        verbose_name_plural = "game"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField("Nume", max_length=120)
    weight = models.CharField("Gramaj", max_length=20)
    unit = models.CharField("U.M.", max_length=10)
    category = models.ForeignKey(
        "Category",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="gama",
    )
    packing = models.CharField("Ambalaj", max_length=25, blank=True)

    class Meta:
        verbose_name = "produs"
        verbose_name_plural = "produse"

    def __str__(self):
        return self.name


class Zone(models.Model):
    name = models.CharField("Zona", max_length=10)
    area = models.CharField("Regiunea", max_length=10)

    class Meta:
        verbose_name = "zona"
        verbose_name_plural = "zone"

    def __str__(self):
        return self.name


class County(models.Model):
    name = models.CharField("Județ", max_length=50, default="ALBA")
    zone = models.ForeignKey(Zone, blank=True, null=True, on_delete=models.SET_NULL)
    area = models.CharField("Regiunea", max_length=10)

    class Meta:
        verbose_name = "județ"
        verbose_name_plural = "județe"

    def __str__(self):
        return self.name


class Agent(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    zone = models.ForeignKey(Zone, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "ASS"
        verbose_name_plural = "ASSi"

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Channel(models.Model):
    name = models.CharField("Tip Canal", max_length=25)

    class Meta:
        verbose_name = "canal"
        verbose_name_plural = "canale"

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField("Numele", max_length=254)
    loc_name = models.CharField("Numele locației", max_length=254, null=True, blank=True)
    CUI = models.IntegerField("CUI", blank=True, null=True)
    channel = models.ForeignKey(
        Channel,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Canal distribuție",
    )
    distributor = models.BooleanField("Distribuitor", blank=True)
    lka = models.BooleanField("Local Key Accout", blank=True)
    zone = models.ForeignKey(
        Zone, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="Zona"
    )
    address = models.CharField("Adresă", max_length=254, blank=True)
    city = models.CharField("Localitatea", max_length=50, blank=True)
    county = models.ForeignKey(County, blank=True, null=True, on_delete=models.SET_NULL)
    contact_person = models.CharField("Persoana de contact", max_length=254, blank=True)
    contact_position = models.CharField("Funcția", max_length=254, blank=True, null=True)
    phone = models.CharField("Telefon", max_length=10, blank=True)
    email = models.EmailField("Email", max_length=100, blank=True)

    class Meta:
        verbose_name = "client"
        verbose_name_plural = "clienți"

    def __str__(self):
        return self.name


class ShopType(models.Model):
    name = models.CharField("Tipul", max_length=50, blank=True, null=True)
    short = models.CharField("Prescurtat", max_length=3, blank=True, null=True)

    class Meta:
        verbose_name = "categorie magazin"
        verbose_name_plural = "categorii magazine"

    def __str__(self):
        return self.short


class Shop(models.Model):
    name = models.CharField("Numele", max_length=254)
    client = models.ForeignKey(Client, blank=True, null=True, on_delete=models.CASCADE)
    shop_type = models.ForeignKey(ShopType, blank=True, null=True, on_delete=models.SET_NULL)
    address = models.CharField("Adresa", max_length=254, blank=True)
    city = models.CharField("Localitatea", max_length=50, blank=True)
    county = models.ForeignKey(County, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "magazin"
        verbose_name_plural = "magazine"

    def __str__(self):
        return self.name


class Visit(models.Model):
    agent = models.ForeignKey(Agent, blank=True, null=True, on_delete=models.SET_NULL)
    client = models.ForeignKey(
        Client, blank=True, null=True, on_delete=models.SET_NULL, related_name="client"
    )
    shop = models.ForeignKey(
        Shop, blank=True, null=True, on_delete=models.SET_NULL, related_name="shop"
    )
    date_created = models.DateTimeField(auto_now_add=True, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    products = models.ManyToManyField(Product, related_name="products")
    products_ordered = models.ManyToManyField(Product, related_name="products_ordered")
    shelf_image = models.ImageField(upload_to="images/", blank=True)
    quantity_ordered = models.IntegerField("Baxuri comandate", blank=True, null=True)
    observations = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "vizită"
        verbose_name_plural = "vizite"

    def __str__(self):
        name = f"{self.client} - {self.shop} - {self.date_created}"
        return name


class WeekPlan(models.Model):
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    agent = models.ForeignKey(Agent, blank=True, null=True, on_delete=models.SET_NULL)
    date_created = models.DateField(default=timezone.now, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    monday_location = models.ForeignKey(
        County,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="monday_location",
    )
    monday_goal = models.TextField(blank=True)
    monday_achieved = models.TextField(blank=True)
    tuesday_location = models.ForeignKey(
        County,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="tuesday_location",
    )
    tuesday_goal = models.TextField(blank=True)
    tuesday_achieved = models.TextField(blank=True)
    wendsday_location = models.ForeignKey(
        County,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="wendsday_location",
    )
    wendsday_goal = models.TextField(blank=True)
    wendsday_achieved = models.TextField(blank=True)
    thursday_location = models.ForeignKey(
        County,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="thursday_location",
    )
    thursday_goal = models.TextField(blank=True)
    thursday_achieved = models.TextField(blank=True)
    friday_location = models.ForeignKey(
        County,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="friday_location",
    )
    friday_goal = models.TextField(blank=True)
    friday_achieved = models.TextField(blank=True)

    class Meta:
        verbose_name = "plan săptămânal"
        verbose_name_plural = "planuri săptămânale"


class Brand(models.Model):
    name = models.CharField("Brand", max_length=100)

    def __str__(self):
        return self.name


class Producer(models.Model):
    name = models.CharField("Producător", max_length=100)

    def __str__(self):
        return self.name


class ProductInfo(models.Model):
    name = models.CharField("Nume produs", max_length=254)
    weight = models.CharField("Gramaj", max_length=20)
    unit = models.CharField("U.M.", max_length=10)
    category = models.ForeignKey(
        "Category",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="gama",
    )
    packing = models.CharField("Ambalaj", max_length=25, blank=True)
    brand = models.ForeignKey("Brand", on_delete=models.CASCADE, verbose_name="brand")
    producer = models.ForeignKey("Producer", on_delete=models.CASCADE, verbose_name="producator")

    class Meta:
        verbose_name = "produs concurență"
        verbose_name_plural = "produse concurență"

    def __str__(self):
        product_name = f"{self.brand} - {self.name}"
        return product_name

    def get_absolute_url(self):
        return reverse("sales:productinfo_detail", args=[str(self.id)])


class PriceEntry(models.Model):
    price_value = models.FloatField(null=True, default=0)
    product = models.ForeignKey(ProductInfo, on_delete=models.CASCADE, related_name="productinfo")
    agent = models.ForeignKey(Agent, blank=True, null=True, on_delete=models.SET_NULL)
    client = models.ForeignKey(
        Client,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="priceinfo_client",
    )
    shop = models.ForeignKey(
        Shop,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="priceinfo_shop",
    )
    date_created = models.DateTimeField(default=timezone.now, blank=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "înregistrare preț"
        verbose_name_plural = "înregistrări preț"

sales/forms.py
from django import forms
from django.forms import modelformset_factory
from .models import Visit, Product, WeekPlan, PriceEntry
from datetime import date


class VisitForm(forms.ModelForm):

    date_created = forms.DateTimeField(
        label="Data vizitei",
        initial=date.today,
        input_formats=["%d/%m/%Y %H:%M"],
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form_input",
            },
        ),
    )

    products = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=[(product.pk, product.name) for product in Product.objects.all()],
        label="Lista de produse",
    )

    products_ordered = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=[(product.pk, product.name) for product in Product.objects.all()],
        label="Produse comandate",
    )

    shelf_image = forms.ImageField(required=False)

    observations = forms.CharField(widget=forms.Textarea(attrs={"rows": "5", "cols": "50"}))

    class Meta:
        model = Visit
        fields = "__all__"
        exclude = ("last-modified",)
        labels = {
            "agent": "Nume ASS",
            "client": "Client",
            "shop": "Magazin",
            "shelf_image": "Adauga imagine raft",
        }


class PlanForm(forms.ModelForm):
    start_date = forms.DateField(
        required=True,
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form_input",
            },
        ),
    )

    end_date = forms.DateField(
        required=True,
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form_input",
            },
        ),
    )

    class Meta:
        model = WeekPlan
        fields = "__all__"
        exclude = ("last-modified",)
        labels = {
            "monday_location": "Locație",
            "monday_goal": "Obiective",
            "monday_achieved": "Realizări",
            "tuesday_location": "Locație",
            "tuesday_goal": "Obiective",
            "tuesday_achieved": "Realizări",
            "wendsday_location": "Locație",
            "wendsday_goal": "Obiective",
            "wendsday_achieved": "Realizări",
            "thursday_location": "Locație",
            "thursday_goal": "Obiective",
            "thursday_achieved": "Realizări",
            "friday_location": "Locație",
            "friday_goal": "Obiective",
            "friday_achieved": "Realizări",
        }


class PriceEntryForm(forms.ModelForm):
    class Meta:
        model = PriceEntry
        fields = "__all__"
        exclude = (
            "date_created",
            "last-modified",
        )
        labels = {"agent": "Nume ASS", "client": "Client", "shop": "Magazin"}


PriceEntryFormSet = modelformset_factory(PriceEntry, fields=("product", "price_value"))

sales/templates/sales/competition_reports.html
{% extends 'sales/base.html' %}

{% block content %}

<main class="container">

    <!-- ### EXPORTA DATELE -->
    <section class="row">
        <div class="col">
            <h1>Rapoarte despre concurență</h1>
            <a href="{% url 'sales:export_competition' %}" class="btn btn-primary">Exporta in Excel</a>
        </div>
    </section>

    <!-- #### RAPORT DUPA PRODUS, CATEGORIE, PRODUCATOR -->
    <section class="row">
        <!-- ### BY PRODUCT & AGENT ### -->
        <div class="col">
            <h3>FILTREAZA DUPA PRODUS</h3>
            <p>Afiseaza informatiile despre concurenta, selectand doar un produs.</p>
            <form action="{% url 'sales:by_product_and_agent' %}" class="form" method="get">
                <!-- by product -->
                <div>
                    <label for="products">Alege produs:</label>
                    <select name="p" id="products">
                        <option disabled selected value> -- toate produsele -- </option>
                        {% for product in products %}
                        <option value="{{ product.id }}">{{ product }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- by agent -->
                <div>
                    <label for="agents">Alege ASS:</label>
                    <select name="a" id="agents">
                        <option disabled selected value> -- toți ASSii -- </option>
                        {% for agent in agents %}
                        <option value="{{ agent.id }}">{{ agent }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <input type="submit" value="Caută" class="btn btn-primary">
                </div>
            </form>
        </div>

        <!-- ### BY CATEGORY & AGENT ### -->
        <div class="col">
            <h3>FILTREAZA DUPA CATEGORIE</h3>
            <p>Afiseaza informatiile despre concurenta, selectand o categorie de produse.</p>
            <form action="{% url 'sales:by_category_and_agent' %}" class="form" method="get">
                <!-- by category -->
                <div>
                    <label for="categories">Alege gama:</label>
                    <select name="cat" id="categories">
                        <option disabled selected value> -- toate gamele -- </option>
                        {% for category in categories %}
                        <option value="{{ category.id }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- by agent -->
                <div>
                    <label for="agents">Alege ASS:</label>
                    <select name="a" id="agents">
                        <option disabled selected value> -- toți ASSii -- </option>
                        {% for agent in agents %}
                        <option value="{{ agent.id }}">{{ agent }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <input type="submit" value="Caută" class="btn btn-primary">
                </div>

            </form>
        </div>

        <!-- ### BY PRODUCER & AGENT ### -->
        <div class="col">
            <h3>FILTREAZA DUPA PRODUCATOR</h3>
            <p>Afiseaza informatiile despre concurenta, selectand un producator.</p>
            <form action="{% url 'sales:by_producer_and_agent' %}" class="form" method="get">
                <!-- by producer  -->
                <div>
                    <label for="producers">Alege producator:</label>
                    <select name="pr" id="producers">
                        <option disabled selected value> -- toți producătorii -- </option>
                        {% for producer in producers %}
                        <option value="{{ producer.id }}">{{ producer }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- by agent -->
                <div>
                    <label for="agents">Alege ASS:</label>
                    <select name="a" id="agents">
                        <option disabled selected value> -- toți ASSii -- </option>
                        {% for agent in agents %}
                        <option value="{{ agent.id }}">{{ agent }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <input type="submit" value="Caută" class="btn btn-primary">
                </div>
            </form>
        </div>
        {% endblock content %}

sales/templates/sales/index.html
{% extends 'sales/base.html' %}

{% block content %}

{% if user.is_authenticated %}
<section class="container">
    <form action="{% url 'sales:index' %}" method="post" class="form">
        <h2>Planificare săptămâna: {{ form.start_date.value|date:"d M Y" }} - {{ form.end_date.value|date:"d M Y" }}
        </h2>
        {% csrf_token %}
        <input type="hidden" name="plan_id" value="{{ plan.id }}">
        <input type="hidden" name="start_date" value="{{ form.start_date.value | date:'Y-m-d' }}">
        <input type="hidden" name="end_date" value="{{ form.end_date.value | date:'Y-m-d' }}">
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary m-2">Salvează modificări</button>
            <a href="{% url 'sales:add_plan' %}" class="btn btn-primary m-2">Planificare nouă</a>
            <button class="btn btn-primary dropdown-toggle m-2" type="button" id="dropdownMenuButton1"
                data-bs-toggle="dropdown" aria-expanded="false">
                Alege alt plan
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                {% for plan in week_plans %}
                <li><a class="dropdown-item" href="?pk={{ plan.id }}">{{ plan.start_date }} - {{ plan.end_date }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <table class="table table-sm">
            <thead>
                <tr>
                    <th scope="col">Zi/Județ</th>
                    <th scope="col">Obiective</th>
                    <th scope="col">Realizări</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="day">Luni</div>
                        <select name="monday_location" id="id_monday_location">
                            {% for county in agent_counties %}
                            <option value="{{ county.id }}" {% if county.id is monday_location %} selected{% endif %}>
                                {{ county.name }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>{{ form.monday_goal }}</td>
                    <td>{{ form.monday_achieved }}</td>
                </tr>
                <tr>
                    <td>
                        <div class="day">Marți</div>
                        <select name="tuesday_location" id="id_tuesday_location">
                            {% for county in agent_counties %}
                            <option value="{{ county.id }}" {% if county.id is tuesday_location %} selected{% endif %}>
                                {{ county.name }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>{{ form.tuesday_goal }}</td>
                    <td>{{ form.tuesday_achieved }}</td>
                </tr>
                <tr>
                    <td>
                        <div class="day">Miercuri</div>
                        <select name="wendsday_location" id="id_wendsday_location">
                            {% for county in agent_counties %}
                            <option value="{{ county.id }}" {% if county.id is wendsday_location %} selected{% endif %}>
                                {{ county.name }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>{{ form.wendsday_goal }}</td>
                    <td>{{ form.wendsday_achieved }}</td>
                </tr>
                <tr>
                    <td>
                        <div class="day">Joi</div>
                        <select name="thursday_location" id="id_thursday_location">
                            {% for county in agent_counties %}
                            <option value="{{ county.id }}" {% if county.id is thursday_location %} selected{% endif %}>
                                {{ county.name }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>{{ form.thursday_goal }}</td>
                    <td>{{ form.thursday_achieved }}</td>
                </tr>
                <tr>
                    <td>
                        <div class="day">Vineri</div>
                        <select name="friday_location" id="id_friday_location">
                            {% for county in agent_counties %}
                            <option value="{{ county.id }}" {% if county.id is friday_location %} selected{% endif %}>
                                {{ county.name }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>{{ form.friday_goal }}</td>
                    <td>{{ form.friday_achieved }}</td>
                </tr>
            </tbody>
        </table>
    </form>
</section>
<section class="container">
    <!-- Vizite -->
    <div class="row">
        <div class="col-6">
            <h1 id="vizite"><a href="{% url 'sales:visits' %}" class="text-decoration-none">Vizite de piață</a></h1>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a href="{% url 'sales:select_client' %}" class="btn btn-primary me-md-2">Vizită nouă</a>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Data și ora</th>
                        <th>Clientul (Magazinul)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for visit in page_obj %}
                    <tr>
                        <td>{{ visit.date_created|date:'d M Y H:m' }}</td>
                        <td><a href="{% url 'sales:visit' visit.id %}">{{ visit.client }} ({{ visit.shop }})</a></td>
                    </tr>
                    {% empty %}
                    <p>Nu au fost realizate vizite încă.</p>
                    {% endfor %}
                </tbody>
            </table>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.previous_page_number }} #vizite">Înapoi</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Înapoi</a></li>
                    {% endif %}

                    {% for page in page_obj.paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page={{ page }} #vizite">{{ page }}</a></li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                            href="?page={{ page_obj.next_page_number }} #vizite">Înainte</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Înainte</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div class="col-6">
            <!-- Informatii concurenta -->
            <h1>Informații concurență</h1>
        </div>
    </div>
</section>
{% else %}
<section class="container">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-4 col-md-offset-6">
                <h2>Salut!</h2>
                <p>Bine ai venit pe platforma de management al vânzărilor Arovit!</p>
                <p>Pentru a putea accesa și adăuga informații, e necesar să te autentifici.</p>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-4 col-md-offset-6 text-center">
                    <a href="{% url 'users:login' %}">
                        <button class="btn btn-primary">Login</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endif %}

{% endblock %}

sales/templates/sales/plan.html
{% extends 'sales/base.html' %}

{% block content %}
<form action="{% url 'sales:index' %}" method="post" class="form">
    <h1>Planificare săptămâna: {{ start_date|date:"d M Y" }} - {{ end_date|date:"d M Y" }}</h1>
    {% csrf_token %}
    <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-primary m-2">Salvează modificări</button>
        <a href="{% url 'sales:add_plan' %}" class="btn btn-primary m-2">Planificare nouă</a>
        <button class="btn btn-primary dropdown-toggle m-2" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Alege alt plan
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            {% for plan in week_plans %}
            <li><a class="dropdown-item" href="{% url 'sales:plan' plan.id }">{{ plan.start_date }} - {{ plan.end_date }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">Zi/Județ</th>
                <th scope="col">Obiective</th>
                <th scope="col">Realizări</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <div class="day">Luni</div>
                    <div>Județ {{ form.monday_location }}</div>
                </td>
                <td>{{ form.monday_goal }}</td>
                <td>{{ form.monday_achieved }}</td>
            </tr>
            <tr>
                <td>
                    <div class="day">Marți</div>
                    <div>Județ {{ form.tuesday_location }}</div>
                </td>
                <td>{{ form.tuesday_goal }}</td>
                <td>{{ form.tuesday_achieved }}</td>
            </tr>
            <tr>
                <td>
                    <div class="day">Miercuri</div>
                    <div>Județ {{ form.wendsday_location }}</div>
                </td>
                <td>{{ form.wendsday_goal }}</td>
                <td>{{ form.wendsday_achieved }}</td>
            </tr>
            <tr>
                <td>
                    <div class="day">Joi</div>
                    <div>Județ {{ form.thursday_location }}</div>
                </td>
                <td>{{ form.thursday_goal }}</td>
                <td>{{ form.thursday_achieved }}</td>
            </tr>
            <tr>
                <td>
                    <div class="day">Vineri</div>
                    <div>Județ {{ form.friday_location }}</div>
                </td>
                <td>{{ form.friday_goal }}</td>
                <td>{{ form.friday_achieved }}</td>
            </tr>
        </tbody>
    </table>
</form>


{% endblock %}